from pathlib import Path
import re, sys

path = Path(sys.argv[1] if len(sys.argv) > 1 else 'bgaplays.html')
text = path.read_text(encoding='utf-8')

if 'bgaplays-credits-v1' in text:
    print('BGA Plays credits patch already applied')
    raise SystemExit(0)


def exact(old, new, label):
    global text
    if old not in text:
        raise SystemExit(f'Missing anchor: {label}')
    text = text.replace(old, new, 1)


def regex(pattern, repl, label, flags=re.S):
    global text
    text2, count = re.subn(pattern, repl, text, count=1, flags=flags)
    if count != 1:
        raise SystemExit(f'Expected one match for {label}, got {count}')
    text = text2

# CSS + feature marker
exact(
    '.advanced-filters{display:none;grid-template-columns:repeat(3,minmax(130px,1fr));gap:6px;margin-top:6px;padding-top:6px;border-top:1px solid var(--border)}.advanced-filters.open{display:grid}',
    '.advanced-filters{display:none;grid-template-columns:repeat(6,minmax(130px,1fr));gap:6px;margin-top:6px;padding-top:6px;border-top:1px solid var(--border)}.advanced-filters.open{display:grid}',
    'advanced filter grid')

css = r'''
/* bgaplays-credits-v1 */
.credits-controls{display:none;gap:8px;flex-wrap:wrap;align-items:end;padding:8px 9px;border-bottom:1px solid var(--border);background:rgba(21,31,52,.55)}.credits-mode .credits-controls{display:flex}.credits-controls .field{min-width:140px;flex:0 1 190px}.credits-controls .btn{align-self:end}
.credit-cell{min-width:220px}.credit-link{border:0;background:none;color:#dce5ff;padding:0;min-height:0;text-align:left;font-weight:800;cursor:pointer}.credit-link:hover{color:#fff;text-decoration:underline}.credit-role{display:inline-flex;align-items:center;min-height:21px;padding:0 6px;border-radius:999px;border:1px solid var(--border);background:var(--surface-3);color:var(--muted);font-size:9px;text-transform:uppercase;font-weight:850;letter-spacing:.05em}.credit-chips{display:flex;gap:5px;flex-wrap:wrap;align-items:center}.credit-chip{display:inline-flex;align-items:center;min-height:25px;padding:0 8px;border:1px solid var(--border);border-radius:999px;background:#111d31;color:#dbe4f7;font-size:10px;font-weight:750;cursor:pointer}.credit-chip:hover{border-color:var(--accent);color:#fff}.credit-groups{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin:0 0 9px}.credit-group{border:1px solid var(--border);background:var(--surface-2);border-radius:10px;padding:8px;min-width:0}.credit-group h4{margin:0 0 6px;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.07em}.credit-empty{color:#63738d;font-size:10px}.credits-progress{height:5px;background:#1b2942;border-radius:999px;overflow:hidden;margin-top:7px}.credits-progress>i{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--accent-2));width:var(--p,0%)}
@media(max-width:1180px){.advanced-filters{grid-template-columns:repeat(3,minmax(130px,1fr))}}
@media(max-width:760px){.advanced-filters{grid-template-columns:1fr 1fr}.credit-groups{grid-template-columns:1fr}.credits-controls{align-items:stretch}.credits-controls .field{flex:1 1 140px}}
'''
exact('dialog{border:1px solid var(--border);', css + '\ndialog{border:1px solid var(--border);', 'dialog css anchor')

# Markup: metadata filters
old_adv = '<div class="advanced-filters" id="advancedFilters"><div class="field"><label for="minAudience">Min audience %</label><input id="minAudience" type="number" min="0" step="0.01" placeholder="0"></div><div class="field"><label for="minPlayed">Min total plays</label><input id="minPlayed" type="number" min="0" step="1" placeholder="0"></div><div class="field"><label for="modelFilter">Model</label><select id="modelFilter"><option value="">Any model</option></select></div></div>'
new_adv = '<div class="advanced-filters" id="advancedFilters"><div class="field"><label for="minAudience">Min audience %</label><input id="minAudience" type="number" min="0" step="0.01" placeholder="0"></div><div class="field"><label for="minPlayed">Min total plays</label><input id="minPlayed" type="number" min="0" step="1" placeholder="0"></div><div class="field"><label for="modelFilter">Model</label><select id="modelFilter"><option value="">Any model</option></select></div><div class="field"><label for="publisherFilter">Publisher</label><input id="publisherFilter" type="search" list="publisherList" placeholder="Any publisher"></div><div class="field"><label for="designerFilter">Designer</label><input id="designerFilter" type="search" list="designerList" placeholder="Any designer"></div><div class="field"><label for="artistFilter">Artist</label><input id="artistFilter" type="search" list="artistList" placeholder="Any artist"></div></div><datalist id="publisherList"></datalist><datalist id="designerList"></datalist><datalist id="artistList"></datalist>'
exact(old_adv, new_adv, 'advanced filters markup')

# Credits tab
exact('<button class="view-tab" data-view="matrix">Game × Time matrix</button>', '<button class="view-tab" data-view="credits">Publishers / People</button><button class="view-tab" data-view="matrix">Game × Time matrix</button>', 'credits tab')

# Credits controls after matrix controls
matrix_anchor = '<div class="matrix-summary" id="matrixSummary" hidden></div>'
credits_controls = '<div class="credits-controls" id="creditsControls"><div class="field"><label for="creditsRole">Rank</label><select id="creditsRole"><option value="publishers">Publishers</option><option value="designers">Designers</option><option value="artists">Artists</option></select></div><div class="field"><label for="creditsMinGames">Min games</label><input id="creditsMinGames" type="number" min="1" step="1" value="1"></div><button class="btn" id="creditsTopBtn">Enrich top 50</button><button class="btn primary" id="creditsLoadBtn">Enrich filtered</button></div>'
exact(matrix_anchor, credits_controls + matrix_anchor, 'credits controls')

# Credits side panel
old_side = '<section class="panel"><div class="panel-head"><h2>BGG collection</h2><button class="btn ghost" id="bggSideRefreshBtn">Refresh</button></div><div class="mini-info" id="bggInfo">Waiting for collection…</div></section></aside>'
new_side = '<section class="panel"><div class="panel-head"><h2>BGG collection</h2><button class="btn ghost" id="bggSideRefreshBtn">Refresh</button></div><div class="mini-info" id="bggInfo">Waiting for collection…</div></section><section class="panel"><div class="panel-head"><h2>Publishers / People</h2><button class="btn ghost" id="creditsSideBtn">Enrich top</button></div><div class="mini-info" id="creditsInfo">Loading metadata…</div></section></aside>'
exact(old_side, new_side, 'credits side panel')

# History credits block
exact('<div class="history-kpis" id="historyKpis"></div><div class="history-toolbar">', '<div class="history-kpis" id="historyKpis"></div><div class="credit-groups" id="historyCredits"></div><div class="history-toolbar">', 'history credits block')

# els/state/sort options
regex(r"const els=\{.*?\};\nconst state=", """const els={gameSearch:$('gameSearch'),yearFilter:$('yearFilter'),monthFilter:$('monthFilter'),modeFilter:$('modeFilter'),minAudience:$('minAudience'),minPlayed:$('minPlayed'),sortSelect:$('sortSelect'),modelFilter:$('modelFilter'),publisherFilter:$('publisherFilter'),designerFilter:$('designerFilter'),artistFilter:$('artistFilter'),publisherList:$('publisherList'),designerList:$('designerList'),artistList:$('artistList'),kpiRecords:$('kpiRecords'),kpiRecordsSub:$('kpiRecordsSub'),kpiGames:$('kpiGames'),kpiMonths:$('kpiMonths'),kpiRange:$('kpiRange'),kpiRealtime:$('kpiRealtime'),kpiTurn:$('kpiTurn'),kpiTotal:$('kpiTotal'),resultsPanel:$('resultsPanel'),resultsTable:$('resultsTable'),tableHead:$('tableHead'),tableBody:$('tableBody'),mobileList:$('mobileList'),pageInfo:$('pageInfo'),pageSize:$('pageSize'),prevBtn:$('prevBtn'),nextBtn:$('nextBtn'),resultTitle:$('resultTitle'),statusDot:$('statusDot'),statusText:$('statusText'),statusMeta:$('statusMeta'),chart:$('chart'),chartMetric:$('chartMetric'),datasetInfo:$('datasetInfo'),bggInfo:$('bggInfo'),creditsInfo:$('creditsInfo'),settingsDialog:$('settingsDialog'),sheetIdInput:$('sheetIdInput'),tabInput:$('tabInput'),customCsvInput:$('customCsvInput'),csvFileInput:$('csvFileInput'),bggUsernameInput:$('bggUsernameInput'),autoBggInput:$('autoBggInput'),bggAliasInput:$('bggAliasInput'),matrixPeriod:$('matrixPeriod'),matrixMetric:$('matrixMetric'),matrixSort:$('matrixSort'),matrixNewest:$('matrixNewest'),matrixBlankZero:$('matrixBlankZero'),matrixTotal:$('matrixTotal'),matrixSummary:$('matrixSummary'),advancedFilters:$('advancedFilters'),creditsRole:$('creditsRole'),creditsMinGames:$('creditsMinGames'),historyDialog:$('historyDialog'),historyIdentity:$('historyIdentity'),historyKpis:$('historyKpis'),historyCredits:$('historyCredits'),historyMetric:$('historyMetric'),historyAdvanced:$('historyAdvanced'),historyChart:$('historyChart'),historyTable:$('historyTable'),historyHead:$('historyHead'),historyBody:$('historyBody'),historyPartialNote:$('historyPartialNote'),historyBggBtn:$('historyBggBtn')};
const state=""", 'els')

regex(r"const state=\{.*?\};\nconst sortOptions=", """const state={rows:[],filtered:[],viewRows:[],view:'records',page:1,pageSize:50,quickRange:'all',sortKey:'period',sortDir:'desc',latestPeriodKey:0,source:null,loadedAt:null,filterTimer:null,thumbs:new Map(),bggMeta:new Map(),aliases:new Map(),bggMatched:0,bggItems:0,bggSource:'Not loaded',bggLoadedAt:null,matrixColumns:[],matrixMax:1,historyMap:new Map(),historyGame:null,historyHighlight:null,advancedOpen:false,studioCredits:new Map(),creditsMap:new Map(),creditsLoadedAt:null,creditsLoading:false,creditsDone:0,creditsTarget:0};
const sortOptions=""", 'state')

regex(r"const sortOptions=\{.*?\};\nfunction parseDuration", """const sortOptions={records:[['period:desc','Latest period'],['period:asc','Oldest period'],['game:asc','Game A–Z'],['audience:desc','Audience share ↓'],['premium:desc','Premium share ↓'],['totalPlayed:desc','Total played ↓'],['realtime:desc','Realtime ↓'],['turnbased:desc','Turn-based ↓'],['duration:desc','Duration ↓'],['timeSpent:desc','Time spent ↓']],games:[['totalPlayed:desc','Total played ↓'],['game:asc','Game A–Z'],['months:desc','Months tracked ↓'],['period:desc','Latest tracked ↓'],['latestAudience:desc','Latest audience ↓'],['latestDelta:desc','Latest change ↓'],['avgAudience:desc','Average audience ↓'],['peakAudience:desc','Peak audience ↓'],['realtime:desc','Realtime ↓'],['turnbased:desc','Turn-based ↓'],['timeSpent:desc','Time spent ↓']],months:[['period:desc','Latest month'],['period:asc','Oldest month'],['games:desc','Games listed ↓'],['avgAudience:desc','Average audience ↓'],['realtime:desc','Realtime ↓'],['turnbased:desc','Turn-based ↓'],['totalPlayed:desc','Total played ↓'],['timeSpent:desc','Time spent ↓']],credits:[['totalPlayed:desc','Total played ↓'],['games:desc','Games represented ↓'],['timeSpent:desc','Time spent ↓'],['avgAudience:desc','Average audience ↓'],['peakAudience:desc','Peak audience ↓'],['realtime:desc','Realtime ↓'],['turnbased:desc','Turn-based ↓'],['credit:asc','Name A–Z']],matrix:[['total:desc','Matrix total ↓'],['game:asc','Game A–Z'],['latest:desc','Latest column ↓']]};
function parseDuration""", 'sort options')

# Credit helper functions before bggMetaFor
credit_helpers = r'''
function decodeHtml(s){const t=document.createElement('textarea');t.innerHTML=String(s||'');return t.value}
function cleanCreditName(s){return decodeHtml(String(s||'')).replace(/\s+/g,' ').trim()}
function creditObj(name,id=''){name=cleanCreditName(name);return name?{name,id:String(id||'')}:null}
function uniqCredits(items){const m=new Map();for(const item of items||[]){const c=typeof item==='string'?creditObj(item):creditObj(item?.name,item?.id);if(!c)continue;const k=normName(c.name);if(!m.has(k)||(!m.get(k).id&&c.id))m.set(k,c)}return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function studioSplit(value,role){const s=cleanCreditName(value);if(!s)return[];if(role==='publishers')return[creditObj(s)].filter(Boolean);return uniqCredits(s.split(/\s*,\s*/).filter(Boolean))}
function creditDataFor(rowOrGame){const game=typeof rowOrGame==='string'?rowOrGame:rowOrGame.game,key=normName(game),seed=state.studioCredits.get(key)||{},rich=state.creditsMap.get(key)||{};return{bggId:rich.bggId||'',bggName:rich.bggName||'',thumb:rich.thumb||'',publishers:uniqCredits([...(seed.publishers||[]),...(rich.publishers||[])]),designers:uniqCredits([...(seed.designers||[]),...(rich.designers||[])]),artists:uniqCredits([...(seed.artists||[]),...(rich.artists||[])])}}
function creditNames(rowOrGame,role){return creditDataFor(rowOrGame)[role]||[]}
function creditMatches(rowOrGame,role,q){if(!q)return true;q=q.toLowerCase();return creditNames(rowOrGame,role).some(c=>c.name.toLowerCase().includes(q))}
function allKnownCredits(role){const m=new Map();for(const rows of state.historyMap.values()){const game=rows[0]?.game;if(!game)continue;for(const c of creditNames(game,role))m.set(normName(c.name),c.name)}return[...m.values()].sort((a,b)=>a.localeCompare(b))}
function populateCreditFilterLists(){for(const [role,list] of [['publishers',els.publisherList],['designers',els.designerList],['artists',els.artistList]])list.innerHTML=allKnownCredits(role).map(n=>`<option value="${esc(n)}"></option>`).join('');refreshCreditsInfo()}
function aliasSearchName(game){const key=normName(game);for(const line of String(settings().bggAliases||'').split(/\r?\n/)){const i=line.indexOf('=');if(i<0)continue;if(normName(line.slice(0,i))===key)return line.slice(i+1).trim()}return game}
function creditChipHtml(c,role){const label=role==='publishers'?'Publisher':role==='designers'?'Designer':'Artist';return`<button class="credit-chip" data-credit-role="${role}" data-credit="${esc(c.name)}" title="Filter by ${label}: ${esc(c.name)}">${esc(c.name)}</button>`}
function historyCreditsHtml(row){const d=creditDataFor(row),groups=[['publishers','Publishers'],['designers','Designers'],['artists','Artists']];return groups.map(([role,label])=>`<section class="credit-group"><h4>${label}</h4><div class="credit-chips">${d[role].length?d[role].map(c=>creditChipHtml(c,role)).join(''):'<span class="credit-empty">Not loaded</span>'}</div></section>`).join('')}
function applyCreditFilter(role,name){const el=role==='publishers'?els.publisherFilter:role==='designers'?els.designerFilter:els.artistFilter;el.value=name;state.advancedOpen=true;els.advancedFilters.classList.add('open');$('advancedBtn').textContent='Less';if(els.historyDialog.open)els.historyDialog.close();setView('games');applyFilters()}
async function loadStudioCredits(){try{const res=await fetch('./bga-studio.csv',{cache:'default'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const rows=parseCsv(await res.text());if(rows.length<2)return;const head=rows[0],idx=Object.fromEntries(head.map((h,i)=>[String(h).trim(),i]));const map=new Map();for(const r of rows.slice(1)){const game=cleanCreditName(r[idx['Game name']]);if(!game)continue;map.set(normName(game),{publishers:studioSplit(r[idx['Publisher']],'publishers'),designers:studioSplit(r[idx['Designer']],'designers'),artists:[]})}state.studioCredits=map;populateCreditFilterLists();if(state.rows.length)applyFilters();console.log(LOG,`Loaded BGA Studio credits for ${map.size} games`)}catch(err){console.warn(LOG,'BGA Studio credits unavailable',err);refreshCreditsInfo()}}
async function loadCreditCache(){try{const cached=await dbGet('credits-v1');if(cached?.entries){state.creditsMap=new Map(cached.entries);state.creditsLoadedAt=cached.loadedAt||null;for(const [key,d] of state.creditsMap){if(d.thumb)state.thumbs.set(key,d.thumb);if(d.bggId)state.bggMeta.set(key,{id:d.bggId,name:d.bggName||'',thumb:d.thumb||''})}populateCreditFilterLists()}}catch(err){console.warn(LOG,'credits cache',err)}}
async function saveCreditCache(){state.creditsLoadedAt=Date.now();await dbSet('credits-v1',{entries:[...state.creditsMap.entries()],loadedAt:state.creditsLoadedAt})}
async function helperXml(query){const urls=[`/api/bgg-helper?${query}`];if(location.hostname!=='board-game-lab.vercel.app')urls.push(`https://board-game-lab.vercel.app/api/bgg-helper?${query}`);let last=null;for(const url of urls){try{const res=await fetch(url,{cache:'no-store'}),txt=await res.text();if(!res.ok)throw new Error(`HTTP ${res.status}`);if(!/^\s*</.test(txt))throw new Error('Not XML');return txt}catch(err){last=err}}throw last||new Error('BGG helper unavailable')}
async function resolveBggId(game){const key=normName(game),known=state.creditsMap.get(key);if(known?.bggId)return known.bggId;const alias=aliasKey(key),collection=state.bggMeta.get(alias)||state.bggMeta.get(key);if(collection?.id)return collection.id;const q=aliasSearchName(game),xmlText=await helperXml(`endpoint=search&type=boardgame&exact=1&query=${encodeURIComponent(q)}`),xml=new DOMParser().parseFromString(xmlText,'text/xml');const items=[...xml.querySelectorAll('item')];if(!items.length)return'';const exactItem=items.find(i=>normName(i.querySelector('name')?.getAttribute('value')||'')===normName(q))||items[0];return exactItem.getAttribute('id')||''}
function parseThingCredits(xmlText){const xml=new DOMParser().parseFromString(xmlText,'text/xml'),item=xml.querySelector('item[type="boardgame"], item');if(!item)throw new Error('BGG Thing returned no game');const links=type=>[...item.querySelectorAll(`link[type="${type}"]`)].map(l=>creditObj(l.getAttribute('value'),l.getAttribute('id'))).filter(Boolean);return{bggId:item.getAttribute('id')||'',bggName:item.querySelector('name[type="primary"]')?.getAttribute('value')||item.querySelector('name')?.getAttribute('value')||'',thumb:item.querySelector('thumbnail')?.textContent?.trim()||'',publishers:uniqCredits(links('boardgamepublisher')),designers:uniqCredits(links('boardgamedesigner')),artists:uniqCredits(links('boardgameartist')),loadedAt:Date.now(),source:'BGG Thing'}}
async function enrichOneCreditGame(game,force=false){const key=normName(game),old=state.creditsMap.get(key);if(!force&&old?.loadedAt&&Date.now()-old.loadedAt<30*24*60*60*1000)return false;const id=await resolveBggId(game);if(!id){state.creditsMap.set(key,{...(old||{}),miss:true,loadedAt:Date.now()});return false}const xml=await helperXml(`endpoint=thing&id=${encodeURIComponent(id)}`),d=parseThingCredits(xml);state.creditsMap.set(key,d);if(d.thumb)state.thumbs.set(key,d.thumb);state.bggMeta.set(key,{id:d.bggId,name:d.bggName,thumb:d.thumb});return true}
function uniqueFilteredGames(){const m=new Map();for(const r of state.filtered)m.set(r.nameKey,r.game);return[...m.values()]}
function rankedGames(limit=50){const m=new Map();for(const r of state.filtered.length?state.filtered:state.rows)m.set(r.game,(m.get(r.game)||0)+r.totalPlayed);return[...m].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(x=>x[0])}
async function enrichCredits(games,force=false){if(state.creditsLoading)return;const uniq=[...new Set(games)].filter(Boolean);if(!uniq.length)return;state.creditsLoading=true;state.creditsDone=0;state.creditsTarget=uniq.length;refreshCreditsInfo();let cursor=0,changed=0;async function worker(){while(cursor<uniq.length){const game=uniq[cursor++];try{if(await enrichOneCreditGame(game,force))changed++}catch(err){console.warn(LOG,'credit enrich',game,err)}state.creditsDone++;refreshCreditsInfo();await new Promise(r=>setTimeout(r,120))}}try{await Promise.all(Array.from({length:Math.min(3,uniq.length)},worker));await saveCreditCache();populateCreditFilterLists();applyFilters();render();console.log(LOG,`Credits enriched: ${changed}/${uniq.length}`)}finally{state.creditsLoading=false;refreshCreditsInfo()}}
function refreshCreditsInfo(){if(!els.creditsInfo)return;const games=[...state.historyMap.values()].map(r=>r[0]?.game).filter(Boolean),covered=games.filter(g=>{const d=creditDataFor(g);return d.publishers.length||d.designers.length||d.artists.length}).length,rich=state.creditsMap.size,pubs=allKnownCredits('publishers').length,designers=allKnownCredits('designers').length,artists=allKnownCredits('artists').length,p=state.creditsTarget?Math.round(state.creditsDone/state.creditsTarget*100):0;els.creditsInfo.innerHTML=`<strong>${full(covered)}</strong> / ${full(games.length)} BGA games have known credits<br><strong>${full(pubs)}</strong> publishers • <strong>${full(designers)}</strong> designers • <strong>${full(artists)}</strong> artists<br>BGA Studio seed: <strong>${full(state.studioCredits.size)}</strong> games<br>BGG enriched/cache: <strong>${full(rich)}</strong> games${state.creditsLoadedAt?` • ${timeAgo(state.creditsLoadedAt)}`:''}${state.creditsLoading?`<br><strong>Enriching ${full(state.creditsDone)} / ${full(state.creditsTarget)}</strong><div class="credits-progress" style="--p:${p}%"><i></i></div>`:'<div class="status-line"><span class="status-pill good">Cached locally in IndexedDB</span></div>'}`}
function buildCreditsRows(){const role=els.creditsRole.value,minGames=Math.max(1,Number(els.creditsMinGames.value)||1),map=new Map();for(const r of state.filtered){for(const c of creditNames(r,role)){const k=normName(c.name);let x=map.get(k);if(!x){x={credit:c.name,creditId:c.id||'',role,gamesSet:new Set(),records:0,totalPlayed:0,realtime:0,turnbased:0,timeSpent:0,sumAudience:0,peakAudience:0};map.set(k,x)}x.gamesSet.add(r.game);x.records++;x.totalPlayed+=r.totalPlayed;x.realtime+=r.realtime;x.turnbased+=r.turnbased;x.timeSpent+=r.timeSpent;x.sumAudience+=r.audience;x.peakAudience=Math.max(x.peakAudience,r.audience)}}state.viewRows=[...map.values()].map(x=>({...x,games:x.gamesSet.size,avgAudience:x.records?x.sumAudience/x.records:0})).filter(x=>x.games>=minGames);sortViewRows()}
'''
exact('function bggMetaFor(row){', credit_helpers + '\nfunction bggMetaFor(row){', 'credit helpers')

# Hydrate should refresh credit lists
exact('refreshBggMatchCount();updateSortOptions();applyFilters()}', 'refreshBggMatchCount();populateCreditFilterLists();updateSortOptions();applyFilters()}', 'hydrate credits refresh')

# Filters
regex(r"function applyFilters\(\)\{.*?\nfunction updateKpis", r'''function applyFilters(){if(!state.rows.length)return;const q=els.gameSearch.value.trim().toLowerCase(),year=Number(els.yearFilter.value)||0,month=Number(els.monthFilter.value)||0,mode=els.modeFilter.value,minAudience=(Number(els.minAudience.value)||0)/100,minPlayed=Number(els.minPlayed.value)||0,model=els.modelFilter.value,pub=els.publisherFilter.value.trim().toLowerCase(),des=els.designerFilter.value.trim().toLowerCase(),art=els.artistFilter.value.trim().toLowerCase();state.filtered=state.rows.filter(r=>{if(q&&!r.gameLower.includes(q))return false;if(year&&r.year!==year)return false;if(month&&r.monthNum!==month)return false;if(minAudience&&r.audience<minAudience)return false;if(minPlayed&&r.totalPlayed<minPlayed)return false;if(model&&r.model!==model)return false;if(pub&&!creditMatches(r,'publishers',pub))return false;if(des&&!creditMatches(r,'designers',des))return false;if(art&&!creditMatches(r,'artists',art))return false;if(mode==='realtime'&&r.realtime<=0)return false;if(mode==='turnbased'&&r.turnbased<=0)return false;if(mode==='both'&&(r.realtime<=0||r.turnbased<=0))return false;return quickRangePass(r)});state.page=1;updateKpis();buildViewRows();render()}
function updateKpis''', 'apply filters')

# View building and sort
regex(r"function buildViewRows\(\)\{.*?\nfunction sortViewRows\(\)\{.*?\nfunction updateSortOptions", r'''function buildViewRows(){if(state.view==='records')state.viewRows=[...state.filtered];else if(state.view==='games'){const map=new Map();for(const r of state.filtered){let g=map.get(r.game);if(!g){g={game:r.game,nameKey:r.nameKey,months:0,period:0,latestAudience:0,latestPremium:0,sumAudience:0,peakAudience:0,realtime:0,turnbased:0,totalPlayed:0,timeSpent:0};map.set(r.game,g)}g.months++;g.sumAudience+=r.audience;g.peakAudience=Math.max(g.peakAudience,r.audience);g.realtime+=r.realtime;g.turnbased+=r.turnbased;g.totalPlayed+=r.totalPlayed;g.timeSpent+=r.timeSpent;if(r.period>g.period){g.period=r.period;g.latestPeriodLabel=r.periodLabel;g.latestAudience=r.audience;g.latestPremium=r.premium}}state.viewRows=[...map.values()].map(g=>{const t=trendMeta(g);return{...g,avgAudience:g.months?g.sumAudience/g.months:0,latestDelta:t.latestDelta}});sortViewRows()}else if(state.view==='months'){const map=new Map();for(const r of state.filtered){let m=map.get(r.period);if(!m){m={period:r.period,periodLabel:r.periodLabel,games:0,sumAudience:0,realtime:0,turnbased:0,totalPlayed:0,timeSpent:0};map.set(r.period,m)}m.games++;m.sumAudience+=r.audience;m.realtime+=r.realtime;m.turnbased+=r.turnbased;m.totalPlayed+=r.totalPlayed;m.timeSpent+=r.timeSpent}state.viewRows=[...map.values()].map(m=>({...m,avgAudience:m.games?m.sumAudience/m.games:0}));sortViewRows()}else if(state.view==='credits')buildCreditsRows();else buildMatrix()}
function sortViewRows(){if(state.view==='matrix'){sortMatrixRows();return}const key=state.sortKey,dir=state.sortDir==='asc'?1:-1;state.viewRows.sort((a,b)=>key==='game'?String(a.game||'').localeCompare(String(b.game||''))*dir:key==='credit'?String(a.credit||'').localeCompare(String(b.credit||''))*dir:((Number(a[key])||0)-(Number(b[key])||0))*dir)}
function updateSortOptions''', 'view rows and sort')

# Columns
regex(r"function columnsForView\(\)\{.*?\nfunction cellValue", r'''function columnsForView(){if(state.view==='records')return[['period','Period'],['game','Game'],['audience','Audience'],['premium','Premium'],['realtime','Realtime'],['turnbased','Turn-based'],['totalPlayed','Total'],['duration','Avg duration'],['timeSpent','Time spent'],['premiumTime','Premium time']];if(state.view==='games')return[['game','Game'],['months','Months'],['period','Latest'],['latestDelta','Δ vs prior'],['latestAudience','Latest audience'],['avgAudience','Avg audience'],['peakAudience','Peak audience'],['realtime','Realtime'],['turnbased','Turn-based'],['totalPlayed','Total played'],['timeSpent','Time spent']];if(state.view==='credits')return[['credit','Name'],['games','Games'],['records','Rows'],['totalPlayed','Total played'],['avgAudience','Avg audience'],['peakAudience','Peak audience'],['realtime','Realtime'],['turnbased','Turn-based'],['timeSpent','Time spent']];return[['period','Period'],['games','Games'],['avgAudience','Avg audience'],['realtime','Realtime'],['turnbased','Turn-based'],['totalPlayed','Total played'],['timeSpent','Time spent']]}
function cellValue''', 'columns')

# Cell formatting for credit/name metrics
exact("if(['realtime','turnbased','totalPlayed','months','games'].includes(key))return full(row[key]);return row[key]??''}", "if(['realtime','turnbased','totalPlayed','months','games','records'].includes(key))return full(row[key]);return row[key]??''}", 'cell value counts')

# Render function
regex(r"function render\(\)\{.*?\nfunction renderMatrix", r'''function render(){els.resultsPanel.classList.toggle('matrix-mode',state.view==='matrix');els.resultsPanel.classList.toggle('credits-mode',state.view==='credits');els.matrixSummary.hidden=state.view!=='matrix';if(state.view==='matrix'){renderMatrix();renderChart();return}els.resultsTable.className='';const total=state.viewRows.length,pages=Math.max(1,Math.ceil(total/state.pageSize));if(state.page>pages)state.page=pages;const start=(state.page-1)*state.pageSize,pageRows=state.viewRows.slice(start,start+state.pageSize),cols=columnsForView(),title=state.view==='records'?'Records':state.view==='games'?'Games summary':state.view==='months'?'Months summary':`${els.creditsRole.options[els.creditsRole.selectedIndex].text} ranking`;els.resultTitle.textContent=`${title} • ${full(total)}`;els.tableHead.innerHTML=`<tr>${cols.map(([key,label])=>`<th data-key="${key}" class="${key==='game'?'game-cell':key==='credit'?'credit-cell':key==='period'?'':'num'}">${label}${state.sortKey===key?(state.sortDir==='asc'?' ↑':' ↓'):''}</th>`).join('')}</tr>`;els.tableBody.innerHTML=pageRows.length?pageRows.map(r=>`<tr>${cols.map(([key])=>key==='game'?`<td class="game-cell">${gameIdentityHtml(r,{spark:state.view==='games'})}</td>`:key==='credit'?`<td class="credit-cell"><button class="credit-link" data-credit-role="${r.role}" data-credit="${esc(r.credit)}">${esc(r.credit)}</button></td>`:`<td class="${key==='period'?'':'num'} ${['audience','latestAudience','avgAudience','peakAudience'].includes(key)?'share':''} ${['premium','latestPremium'].includes(key)?'premium':''}">${key==='latestDelta'?cellValue(r,key):esc(cellValue(r,key))}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="empty">No matching rows${state.view==='credits'?' — enrich metadata or loosen filters':''}</td></tr>`;els.mobileList.innerHTML=pageRows.length?pageRows.map(mobileCard).join(''):'<div class="empty">No matching rows</div>';els.pageInfo.textContent=total?`${full(start+1)}–${full(Math.min(start+state.pageSize,total))} of ${full(total)} • Page ${state.page}/${pages}`:'0 results';els.prevBtn.disabled=state.page<=1;els.nextBtn.disabled=state.page>=pages;bindGameClicks();bindCreditClicks();renderChart()}
function renderMatrix''', 'render')

# Mobile cards
regex(r"function mobileCard\(r\)\{.*?\nfunction renderChart", r'''function mobileCard(r){if(state.view==='records')return`<div class="mobile-card"><div class="row1">${gameIdentityHtml(r)}<div class="period ${isCurrentPeriod(r.period)?'partial':''}">${esc(displayPeriod(r))}</div></div><div class="mobile-stats"><span>Audience <b>${pct(r.audience)}</b></span><span>Premium <b>${pct(r.premium)}</b></span><span>Realtime <b>${full(r.realtime)}</b></span><span>Turn-based <b>${full(r.turnbased)}</b></span><span>Total <b>${full(r.totalPlayed)}</b></span><span>Duration <b>${esc(r.durationRaw||'—')}</b></span></div></div>`;if(state.view==='games')return`<div class="mobile-card"><div class="row1">${gameIdentityHtml(r,{spark:true})}<div class="period ${isCurrentPeriod(r.period)?'partial':''}">${esc(r.latestPeriodLabel||'')}${isCurrentPeriod(r.period)?' *':''}</div></div><div class="mobile-stats"><span>Months <b>${full(r.months)}</b></span><span>Δ prior <b>${deltaHtml(r.latestDelta,isCurrentPeriod(r.period))}</b></span><span>Latest audience <b>${pct(r.latestAudience)}</b></span><span>Peak audience <b>${pct(r.peakAudience)}</b></span><span>Total played <b>${full(r.totalPlayed)}</b></span><span>Time spent <b>${compact(r.timeSpent)} hr</b></span></div></div>`;if(state.view==='credits')return`<div class="mobile-card"><div class="row1"><button class="credit-link" data-credit-role="${r.role}" data-credit="${esc(r.credit)}">${esc(r.credit)}</button><span class="credit-role">${r.role.slice(0,-1)}</span></div><div class="mobile-stats"><span>Games <b>${full(r.games)}</b></span><span>Total played <b>${full(r.totalPlayed)}</b></span><span>Avg audience <b>${pct(r.avgAudience)}</b></span><span>Peak audience <b>${pct(r.peakAudience)}</b></span><span>Realtime <b>${full(r.realtime)}</b></span><span>Turn-based <b>${full(r.turnbased)}</b></span></div></div>`;return`<div class="mobile-card"><div class="row1"><strong>${esc(r.periodLabel)}${isCurrentPeriod(r.period)?' *':''}</strong><div class="period">${full(r.games)} games</div></div><div class="mobile-stats"><span>Avg audience <b>${pct(r.avgAudience)}</b></span><span>Realtime <b>${full(r.realtime)}</b></span><span>Turn-based <b>${full(r.turnbased)}</b></span><span>Total <b>${full(r.totalPlayed)}</b></span></div></div>`}
function renderChart''', 'mobile cards')

# Bind credit clicks after bindGameClicks
exact("function bindGameClicks(root=document){root.querySelectorAll('.game-link[data-game]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',e=>{e.stopPropagation();openGameHistory(btn.dataset.game)})})}", "function bindGameClicks(root=document){root.querySelectorAll('.game-link[data-game]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',e=>{e.stopPropagation();openGameHistory(btn.dataset.game)})})}\nfunction bindCreditClicks(root=document){root.querySelectorAll('[data-credit-role][data-credit]').forEach(btn=>{if(btn.dataset.creditBound)return;btn.dataset.creditBound='1';btn.addEventListener('click',e=>{e.stopPropagation();applyCreditFilter(btn.dataset.creditRole,btn.dataset.credit)})})}", 'bind credits')

# Set view and clear filters
exact("function setView(view){state.view=view;state.page=1;document.querySelectorAll('.view-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));updateSortOptions();buildViewRows();render()}", "function setView(view){state.view=view;state.page=1;document.querySelectorAll('.view-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));updateSortOptions();buildViewRows();render()}", 'set view anchor')
exact("function clearFilters(){els.gameSearch.value='';els.yearFilter.value='';els.monthFilter.value='';els.modeFilter.value='';els.minAudience.value='';els.minPlayed.value='';els.modelFilter.value='';state.quickRange='all';", "function clearFilters(){els.gameSearch.value='';els.yearFilter.value='';els.monthFilter.value='';els.modeFilter.value='';els.minAudience.value='';els.minPlayed.value='';els.modelFilter.value='';els.publisherFilter.value='';els.designerFilter.value='';els.artistFilter.value='';state.quickRange='all';", 'clear filters')

# Export credits view
regex(r"function exportCurrent\(\)\{.*?\nfunction downloadCsv", r'''function exportCurrent(){if(!state.viewRows.length)return;let lines=[];const quote=v=>`"${String(v??'').replace(/"/g,'""')}"`;if(state.view==='matrix'){const headers=['Game',...state.matrixColumns.map(c=>c.label),...(els.matrixTotal.checked?['Total']:[])];lines=[headers.map(quote).join(',')];for(const g of state.viewRows)lines.push([g.game,...state.matrixColumns.map(c=>g.values.get(c.key)||0),...(els.matrixTotal.checked?[g.total]:[])].map(quote).join(','))}else{const cols=columnsForView();lines=[cols.map(c=>quote(c[1])).join(',')];for(const r of state.viewRows)lines.push(cols.map(([key])=>quote(key==='latestDelta'?(r.latestDelta??''):cellValue(r,key))).join(','))}downloadCsv(lines.join('\r\n'),`bga-plays-${state.view}-${new Date().toISOString().slice(0,10)}.csv`)}
function downloadCsv''', 'export current')

# Refresh BGG should also refresh credit info
exact('refreshBggMatchCount();render();if(cached.loadedAt', 'refreshBggMatchCount();refreshCreditsInfo();render();if(cached.loadedAt', 'bgg cache refresh credits')
exact('refreshBggMatchCount();render()}catch(err)', 'refreshBggMatchCount();refreshCreditsInfo();render()}catch(err)', 'bgg live refresh credits')

# History includes credits
regex(r"function renderHistory\(\)\{.*?\nfunction renderHistoryChart", r'''function renderHistory(){const rows=fullHistory(state.historyGame),latest=rows.at(-1),prev=rows.at(-2);if(!latest)return;const total=rows.reduce((s,r)=>s+r.totalPlayed,0),peak=rows.reduce((a,b)=>b.totalPlayed>a.totalPlayed?b:a,rows[0]),avgAud=rows.reduce((s,r)=>s+r.audience,0)/rows.length,delta=prev&&prev.totalPlayed?(latest.totalPlayed-prev.totalPlayed)/prev.totalPlayed:null,partial=isCurrentPeriod(latest.period),meta=bggMetaFor(latest),credits=creditDataFor(latest);els.historyIdentity.innerHTML=`${thumbHtml(latest)}<div class="history-title"><h3>${esc(latest.game)}</h3><div class="sub">Complete history • ${full(rows.length)} months • ${esc(rows[0].periodLabel)} → ${esc(latest.periodLabel)}${partial?' *':''}</div></div>`;els.historyKpis.innerHTML=`<div class="history-kpi"><div class="label">Months tracked</div><div class="value">${full(rows.length)}</div></div><div class="history-kpi"><div class="label">Latest total</div><div class="value">${full(latest.totalPlayed)}${partial?' *':''}</div></div><div class="history-kpi"><div class="label">Δ vs prior</div><div class="value">${deltaHtml(delta,partial)}</div></div><div class="history-kpi"><div class="label">Peak month</div><div class="value">${full(peak.totalPlayed)}</div><div class="modal-note">${esc(peak.periodLabel)}</div></div><div class="history-kpi"><div class="label">Avg audience</div><div class="value">${pct(avgAud)}</div></div>`;els.historyCredits.innerHTML=historyCreditsHtml(latest);bindCreditClicks(els.historyCredits);els.historyPartialNote.classList.toggle('show',partial);const id=credits.bggId||meta?.id||'';els.historyBggBtn.hidden=!id;els.historyBggBtn.dataset.id=id;renderHistoryChart();renderHistoryTable();const games=[...state.historyMap.values()].map(x=>x[0].game).sort((a,b)=>a.localeCompare(b)),idx=games.findIndex(g=>normName(g)===normName(state.historyGame));$('historyPrevBtn').disabled=idx<=0;$('historyNextBtn').disabled=idx<0||idx>=games.length-1;$('historyPrevBtn').dataset.game=games[idx-1]||'';$('historyNextBtn').dataset.game=games[idx+1]||''}
function renderHistoryChart''', 'history credits render')

# Exclude credits controls from generic filters
exact("'matrixTotal','historyMetric','historyAdvanced']", "'matrixTotal','historyMetric','historyAdvanced','creditsRole','creditsMinGames']", 'generic listener exclusions')

# Event listeners for credits controls
anchor = "[els.matrixPeriod,els.matrixMetric,els.matrixSort,els.matrixNewest,els.matrixBlankZero,els.matrixTotal].forEach(el=>el.addEventListener('change',()=>{state.page=1;if(state.view==='matrix')buildViewRows();render()}));"
listeners = anchor + "\nels.creditsRole.addEventListener('change',()=>{state.page=1;if(state.view==='credits'){buildViewRows();updateSortOptions();render()}});els.creditsMinGames.addEventListener('input',()=>{clearTimeout(state.filterTimer);state.filterTimer=setTimeout(()=>{if(state.view==='credits'){buildViewRows();render()}},120)});$('creditsLoadBtn').addEventListener('click',()=>enrichCredits(uniqueFilteredGames()));$('creditsTopBtn').addEventListener('click',()=>enrichCredits(rankedGames(50)));$('creditsSideBtn').addEventListener('click',()=>enrichCredits(rankedGames(50)));"
exact(anchor, listeners, 'credits listeners')

# Clear cache should clear credits state too
exact("state.thumbs=new Map();state.bggMeta=new Map();state.bggItems=0;state.bggSource='Not loaded';refreshBggMatchCount();render()", "state.thumbs=new Map();state.bggMeta=new Map();state.bggItems=0;state.bggSource='Not loaded';state.creditsMap=new Map();state.creditsLoadedAt=null;refreshBggMatchCount();populateCreditFilterLists();render()", 'clear credits cache')

# Initial load: credit cache + studio seed; then lazy top enrichment after collection
regex(r"async function init\(\)\{.*?\}init\(\);", r'''async function init(){console.log(`${LOG} Starting BGA Plays Explorer v4 credits`);const s=settings();state.aliases=parseAliases(s.bggAliases);const cached=await loadCachedFirst();if(!cached)await loadLive();await loadCreditCache();await loadStudioCredits();refreshBggMatchCount();populateCreditFilterLists();applyFilters();if(s.autoBgg)loadBggCollection(false).then(()=>{if(state.creditsMap.size<30)setTimeout(()=>enrichCredits(rankedGames(30)),600)})}init();''', 'init')

# Sanity markers
required = ['publisherFilter','designerFilter','artistFilter','data-view="credits"','function buildCreditsRows','function enrichCredits','historyCreditsHtml','bgaplays-credits-v1']
for marker in required:
    if marker not in text:
        raise SystemExit(f'Missing post-patch marker: {marker}')

path.write_text(text, encoding='utf-8')
print('Applied BGA Plays publisher/designer/artist credits patch')
