from pathlib import Path

TARGET = Path("bgg-contacts.html")
s = TARGET.read_text(encoding="utf-8")


def replace_once(old: str, new: str, label: str) -> None:
    global s
    count = s.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly 1 match, found {count}")
    s = s.replace(old, new, 1)


# 1) Contact layout / responsive polish.
replace_once(
    "</style><style id=\"plain-access-fix\">",
    """\n/* Contacts CRM upgrade */\n.contactHeader{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:10px}.contactHeader h2{margin:0;font-size:18px}.contactHeader .meta{margin-top:3px}.contactTable{min-width:1450px}.editGrid select{width:100%;margin-top:4px}.contactSectionLabel{grid-column:1/-1;margin-top:4px;padding-top:10px;border-top:1px solid #203149;color:#91a0b5;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.preferredTag{display:inline-block;margin-left:5px;padding:2px 6px;border-radius:999px;background:#13243a;border:1px solid #30445f;color:#b9c7d8;font-size:9px;font-weight:800;text-transform:uppercase}.contactDetail.discord{color:#c9b7ff}.contactModalActions{justify-content:space-between;margin-top:16px}.contactModalActions .rightActions{display:flex;gap:7px}.contactFormHint{margin-top:8px;padding:8px 10px;border:1px solid #203149;border-radius:9px;background:#091524;color:#91a0b5;font-size:11px}@media(max-width:800px){.contactHeader{align-items:stretch;flex-direction:column}.contactTable{min-width:1450px}.contactModalActions{align-items:stretch;flex-direction:column-reverse}.contactModalActions .rightActions{display:grid;grid-template-columns:1fr}.contactModalActions .btn{width:100%}.contactSectionLabel{grid-column:auto}}\n</style><style id=\"plain-access-fix\">""",
    "contact CRM CSS",
)

# 2) Contacts screen header and Discord missing-data filter.
replace_once(
    '<section id="contacts" class="hidden"><div class="panel"><input id="csearch" style="width:100%" placeholder="Search contacts">',
    '<section id="contacts" class="hidden"><div class="panel"><div class="contactHeader"><div><h2>Contacts</h2><div class="meta">BGG-linked outreach contacts with email, BGG, Discord and follow-up details.</div></div></div><input id="csearch" style="width:100%" placeholder="Search name, organization, email, BGG or Discord">',
    "contacts header",
)
replace_once(
    '<button class="btn contactFilterBtn missingBtn" data-missing="bgg">BGG</button><button class="btn contactFilterBtn missingBtn" data-missing="date">Date</button>',
    '<button class="btn contactFilterBtn missingBtn" data-missing="bgg">BGG</button><button class="btn contactFilterBtn missingBtn" data-missing="discord">Discord</button><button class="btn contactFilterBtn missingBtn" data-missing="date">Date</button>',
    "Discord missing filter",
)

# 3) Expand the contact drawer. The same drawer is now used for both CREATE and EDIT.
old_modal = '<div id="contactModal" class="modal"><div class="box"><div class="head"><div><h2 id="ctitle"></h2><div id="cmeta" class="meta"></div></div><button class="btn xbtn" data-close="contactModal">×</button></div><div class="editGrid"><label>First Contact Date<input id="editDate" type="date"></label><label>Email<input id="editEmail"></label><label>BGG Username<input id="editBgg"></label><label>Source Game<input id="editSource"></label><label>Heard Back?<div class="heardToggle"><button id="heardYes" class="btn">Yes</button><button id="heardNo" class="btn">No</button></div></label><label class="full">Notes<textarea id="editNotes"></textarea></label></div><div class="actions"><button id="deleteContact" class="btn">Delete</button><button id="saveContact" class="btn primary">Save Changes</button></div></div></div>'
new_modal = '<div id="contactModal" class="modal"><div class="box"><div class="head"><div><h2 id="ctitle"></h2><div id="cmeta" class="meta"></div></div><button class="btn xbtn" data-close="contactModal">×</button></div><div id="contactFormHint" class="contactFormHint"></div><div class="editGrid"><div class="contactSectionLabel">Contact</div><label>Name<input id="editName" autocomplete="name"></label><label>Organization<input id="editOrganization" placeholder="Publisher / studio / company"></label><label>Email<input id="editEmail" type="email" autocomplete="email"></label><label>BGG Username<input id="editBgg" autocomplete="off"></label><label>Discord Username<input id="editDiscord" autocomplete="off" placeholder="e.g. sjthekiwi"></label><label>Preferred Contact<select id="editPreferred"><option value="">Not set</option><option value="email">Email</option><option value="bgg">BGG</option><option value="discord">Discord</option><option value="other">Other</option></select></label><div class="contactSectionLabel">Outreach</div><label>First Contact Date<input id="editDate" type="date"></label><label>Source Game<input id="editSource"></label><label>Heard Back?<div class="heardToggle"><button id="heardYes" class="btn" type="button">Yes</button><button id="heardNo" class="btn" type="button">No</button></div></label><label class="full">Notes<textarea id="editNotes" rows="5"></textarea></label></div><div class="actions contactModalActions"><button id="deleteContact" class="btn danger">Delete</button><div class="rightActions"><button id="saveContact" class="btn primary">Save Changes</button></div></div></div></div>'
replace_once(old_modal, new_modal, "contact modal")

# 4) Track create-vs-edit state and return to the source game after a new save.
replace_once(
    'let games=[],contacts=[],pipelineGames=[],game=null,editContact=null,modalHeard=false,contactView=',
    'let games=[],contacts=[],pipelineGames=[],game=null,editContact=null,draftContact=null,contactReturnGameId=null,modalHeard=false,contactView=',
    "contact state",
)

# 5) Saving a BGG publisher/designer/artist now opens the full contact form first.
old_save_binding = "document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{let p=findPerson(b.dataset.save),ex=await dbApi('bg_contact','READ',{filters:{bgg_type:p.type,bgg_id:+p.id},limit:1});if(!ex.length)await dbApi('bg_contact','CREATE',{data:{bgg_type:p.type,bgg_id:+p.id,name:p.name,source_game_id:+game.id,source_game_name:game.title,heard_back:false}});await loadContacts();openGame(game.id)})"
new_save_binding = "document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{let p=findPerson(b.dataset.save),ex=await dbApi('bg_contact','READ',{filters:{bgg_type:p.type,bgg_id:+p.id},limit:1});contactReturnGameId=game.id;closeM('gameModal');if(ex.length)openContact(ex[0].id);else openNewContact(p,game)})"
replace_once(old_save_binding, new_save_binding, "single-step Save Contact flow")

# 6) Search/filter all new fields.
old_filtered = "function filteredContacts(){let q=$('csearch').value.toLowerCase();return contacts.filter(c=>{if(q&&![c.name,c.email,c.bgg_username,c.notes,c.first_contact_date,c.source_game_name,c.heard_back?'replied heard back yes':'no reply'].join(' ').toLowerCase().includes(q))return false;if(contactType!=='any'&&c.bgg_type!==contactType)return false;if(contactReply==='yes'&&!c.heard_back)return false;if(contactReply==='no'&&c.heard_back)return false;if(contactMissing.has('email')&&String(c.email||'').trim())return false;if(contactMissing.has('bgg')&&String(c.bgg_username||'').trim())return false;if(contactMissing.has('date')&&String(c.first_contact_date||'').trim())return false;if(contactMissing.has('game')&&String(c.source_game_name||'').trim())return false;return true})}"
new_filtered = "function filteredContacts(){let q=$('csearch').value.toLowerCase();return contacts.filter(c=>{if(q&&![c.name,c.organization,c.email,c.bgg_username,c.discord_username,c.preferred_contact_method,c.notes,c.first_contact_date,c.source_game_name,c.heard_back?'replied heard back yes':'no reply'].join(' ').toLowerCase().includes(q))return false;if(contactType!=='any'&&c.bgg_type!==contactType)return false;if(contactReply==='yes'&&!c.heard_back)return false;if(contactReply==='no'&&c.heard_back)return false;if(contactMissing.has('email')&&String(c.email||'').trim())return false;if(contactMissing.has('bgg')&&String(c.bgg_username||'').trim())return false;if(contactMissing.has('discord')&&String(c.discord_username||'').trim())return false;if(contactMissing.has('date')&&String(c.first_contact_date||'').trim())return false;if(contactMissing.has('game')&&String(c.source_game_name||'').trim())return false;return true})}"
replace_once(old_filtered, new_filtered, "contact filtering")

# 7) Contact table: expose organization, Discord and preferred method inline.
old_render_table = "function renderTable(a){$('clist').className='tableWrap';$('clist').innerHTML=`<table class=\"contactTable\"><thead><tr><th>Name</th><th>Type</th><th>BGG ID</th><th>Email</th><th>BGG User</th><th>First Contact</th><th>Heard Back</th><th>Source Game</th><th>Notes</th></tr></thead><tbody>${a.map(c=>editRow(c)).join('')}</tbody></table>`;document.querySelectorAll('[data-auto-row]').forEach(x=>{x.onchange=()=>autoSaveRow(+x.dataset.autoRow,x);if(x.type==='text')x.onblur=()=>autoSaveRow(+x.dataset.autoRow,x)})}"
new_render_table = "function preferredOptions(v){return ['','email','bgg','discord','other'].map(x=>`<option value=\"${x}\" ${v===x?'selected':''}>${x?cap(x):'—'}</option>`).join('')}function renderTable(a){$('clist').className='tableWrap';$('clist').innerHTML=`<table class=\"contactTable\"><thead><tr><th>Name</th><th>Type</th><th>BGG ID</th><th>Organization</th><th>Email</th><th>BGG User</th><th>Discord</th><th>Preferred</th><th>First Contact</th><th>Heard Back</th><th>Source Game</th><th>Notes</th></tr></thead><tbody>${a.map(c=>editRow(c)).join('')}</tbody></table>`;document.querySelectorAll('[data-auto-row]').forEach(x=>{x.onchange=()=>autoSaveRow(+x.dataset.autoRow,x);if(x.type==='text'||x.type==='email')x.onblur=()=>autoSaveRow(+x.dataset.autoRow,x)})}"
replace_once(old_render_table, new_render_table, "contact table")

old_edit_row = "function editRow(c){return `<tr><td><b>${e(c.name)}</b></td><td>${e(c.bgg_type.replace('boardgame',''))}</td><td>${e(c.bgg_id)}</td><td><input data-auto-row=\"${c.id}\" id=\"re-email-${c.id}\" value=\"${e(c.email||'')}\"></td><td><input data-auto-row=\"${c.id}\" id=\"re-bgg-${c.id}\" value=\"${e(c.bgg_username||'')}\"></td><td><input data-auto-row=\"${c.id}\" id=\"re-date-${c.id}\" type=\"date\" value=\"${e(c.first_contact_date||'')}\"></td><td><button id=\"re-heard-${c.id}\" class=\"btn smallBtn ${c.heard_back?'yesBtn':'noBtn'}\" data-heard=\"${c.heard_back?'1':'0'}\" onclick=\"toggleRowHeard(${c.id})\">${c.heard_back?'Yes':'No'}</button></td><td><input data-auto-row=\"${c.id}\" class=\"wideInput\" id=\"re-source-${c.id}\" value=\"${e(c.source_game_name||'')}\"></td><td><input data-auto-row=\"${c.id}\" class=\"notesInput\" id=\"re-notes-${c.id}\" value=\"${e(c.notes||'')}\"></td></tr>`}"
new_edit_row = "function editRow(c){return `<tr><td><b>${e(c.name)}</b></td><td>${e(c.bgg_type.replace('boardgame',''))}</td><td>${e(c.bgg_id)}</td><td><input data-auto-row=\"${c.id}\" id=\"re-org-${c.id}\" value=\"${e(c.organization||'')}\"></td><td><input data-auto-row=\"${c.id}\" id=\"re-email-${c.id}\" type=\"email\" value=\"${e(c.email||'')}\"></td><td><input data-auto-row=\"${c.id}\" id=\"re-bgg-${c.id}\" value=\"${e(c.bgg_username||'')}\"></td><td><input data-auto-row=\"${c.id}\" id=\"re-discord-${c.id}\" value=\"${e(c.discord_username||'')}\"></td><td><select data-auto-row=\"${c.id}\" id=\"re-preferred-${c.id}\">${preferredOptions(c.preferred_contact_method||'')}</select></td><td><input data-auto-row=\"${c.id}\" id=\"re-date-${c.id}\" type=\"date\" value=\"${e(c.first_contact_date||'')}\"></td><td><button id=\"re-heard-${c.id}\" class=\"btn smallBtn ${c.heard_back?'yesBtn':'noBtn'}\" data-heard=\"${c.heard_back?'1':'0'}\" onclick=\"toggleRowHeard(${c.id})\">${c.heard_back?'Yes':'No'}</button></td><td><input data-auto-row=\"${c.id}\" class=\"wideInput\" id=\"re-source-${c.id}\" value=\"${e(c.source_game_name||'')}\"></td><td><input data-auto-row=\"${c.id}\" class=\"notesInput\" id=\"re-notes-${c.id}\" value=\"${e(c.notes||'')}\"></td></tr>`}"
replace_once(old_edit_row, new_edit_row, "contact edit row")

old_save_row = "async function saveRow(id){let data={email:$('re-email-'+id).value.trim()||null,bgg_username:$('re-bgg-'+id).value.trim()||null,first_contact_date:$('re-date-'+id).value||null,heard_back:$('re-heard-'+id).dataset.heard==='1',source_game_name:$('re-source-'+id).value.trim()||null,notes:$('re-notes-'+id).value.trim()||null,updated_at:new Date().toISOString()};await dbApi('bg_contact','UPDATE',{filters:{id},data});let c=contacts.find(x=>x.id===id);if(c)Object.assign(c,data)}"
new_save_row = "async function saveRow(id){let data={organization:$('re-org-'+id).value.trim()||null,email:$('re-email-'+id).value.trim()||null,bgg_username:$('re-bgg-'+id).value.trim()||null,discord_username:$('re-discord-'+id).value.trim()||null,preferred_contact_method:$('re-preferred-'+id).value||null,first_contact_date:$('re-date-'+id).value||null,heard_back:$('re-heard-'+id).dataset.heard==='1',source_game_name:$('re-source-'+id).value.trim()||null,notes:$('re-notes-'+id).value.trim()||null,updated_at:new Date().toISOString()};await dbApi('bg_contact','UPDATE',{filters:{id},data});let c=contacts.find(x=>x.id===id);if(c)Object.assign(c,data)}"
replace_once(old_save_row, new_save_row, "inline contact save")

# 8) Card view: surface the communication channels at a glance.
old_cards = "function renderCards(a){$('clist').className='contacts';$('clist').innerHTML=a.map(c=>`<article class=\"card contact\" data-c=\"${c.id}\"><div class=\"contactTitle\">${e(c.name)}</div><span class=\"contactType\">${e(c.bgg_type.replace('boardgame',''))}</span> <span class=\"replyTag ${c.heard_back?'replyYes':'replyNo'}\">${c.heard_back?'Replied':'No Reply'}</span><div class=\"meta\">BGG ID ${c.bgg_id}</div>${c.email?`<div class=\"contactDetail\">✉ ${e(c.email)}</div>`:''}${c.bgg_username?`<div class=\"contactDetail\">BGG: ${e(c.bgg_username)}</div>`:''}${c.first_contact_date?`<div class=\"contactDetail\">First contact: ${e(c.first_contact_date)}</div>`:''}${c.source_game_name?`<div class=\"meta\">Source: ${e(c.source_game_name)}</div>`:''}</article>`).join('');document.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>openContact(+x.dataset.c))}"
new_cards = "function renderCards(a){$('clist').className='contacts';$('clist').innerHTML=a.map(c=>`<article class=\"card contact\" data-c=\"${c.id}\"><div class=\"contactTitle\">${e(c.name)}${c.preferred_contact_method?`<span class=\"preferredTag\">${e(c.preferred_contact_method)}</span>`:''}</div>${c.organization?`<div class=\"meta\">${e(c.organization)}</div>`:''}<span class=\"contactType\">${e(c.bgg_type.replace('boardgame',''))}</span> <span class=\"replyTag ${c.heard_back?'replyYes':'replyNo'}\">${c.heard_back?'Replied':'No Reply'}</span><div class=\"meta\">BGG ID ${c.bgg_id}</div>${c.email?`<div class=\"contactDetail\">✉ ${e(c.email)}</div>`:''}${c.bgg_username?`<div class=\"contactDetail\">BGG: ${e(c.bgg_username)}</div>`:''}${c.discord_username?`<div class=\"contactDetail discord\">Discord: ${e(c.discord_username)}</div>`:''}${c.first_contact_date?`<div class=\"contactDetail\">First contact: ${e(c.first_contact_date)}</div>`:''}${c.source_game_name?`<div class=\"meta\">Source: ${e(c.source_game_name)}</div>`:''}${c.notes?`<div class=\"contactNote\">${e(c.notes)}</div>`:''}</article>`).join('');document.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>openContact(+x.dataset.c))}"
replace_once(old_cards, new_cards, "contact cards")

# 9) Drawer behavior for edit and create.
old_open_contact = "function setModalHeard(v){modalHeard=!!v;$('heardYes').className='btn '+(modalHeard?'yesBtn':'');$('heardNo').className='btn '+(!modalHeard?'noBtn':'')}function openContact(id){editContact=contacts.find(c=>c.id===id);if(!editContact)return;$('ctitle').textContent=editContact.name;$('cmeta').textContent=editContact.bgg_type.replace('boardgame','')+' • BGG ID '+editContact.bgg_id;$('editDate').value=editContact.first_contact_date||'';$('editEmail').value=editContact.email||'';$('editBgg').value=editContact.bgg_username||'';$('editSource').value=editContact.source_game_name||'';$('editNotes').value=editContact.notes||'';setModalHeard(editContact.heard_back);$('contactModal').classList.add('open')}"
new_open_contact = "function setModalHeard(v){modalHeard=!!v;$('heardYes').className='btn '+(modalHeard?'yesBtn':'');$('heardNo').className='btn '+(!modalHeard?'noBtn':'')}function fillContactForm(c){$('editName').value=c.name||'';$('editOrganization').value=c.organization||'';$('editDate').value=c.first_contact_date||'';$('editEmail').value=c.email||'';$('editBgg').value=c.bgg_username||'';$('editDiscord').value=c.discord_username||'';$('editPreferred').value=c.preferred_contact_method||'';$('editSource').value=c.source_game_name||'';$('editNotes').value=c.notes||'';setModalHeard(c.heard_back)}function openContact(id){editContact=contacts.find(c=>c.id===id);draftContact=null;if(!editContact)return;$('ctitle').textContent='Edit Contact';$('cmeta').textContent=editContact.bgg_type.replace('boardgame','')+' • BGG ID '+editContact.bgg_id;$('contactFormHint').textContent='Update any contact channel here. Changes are saved to the existing BGG-linked contact.';fillContactForm(editContact);$('deleteContact').classList.remove('hidden');$('saveContact').textContent='Save Changes';$('contactModal').classList.add('open')}function openNewContact(p,g){editContact=null;draftContact={bgg_type:p.type,bgg_id:+p.id,name:p.name,source_game_id:g?+g.id:null,source_game_name:g?.title||'',heard_back:false};$('ctitle').textContent='Add Contact';$('cmeta').textContent=p.type.replace('boardgame','')+' • BGG ID '+p.id;$('contactFormHint').textContent='Add email, BGG username or Discord now so you do not need a second edit step.';fillContactForm(draftContact);$('deleteContact').classList.add('hidden');$('saveContact').textContent='Add Contact';$('contactModal').classList.add('open')}"
replace_once(old_open_contact, new_open_contact, "contact drawer behavior")

# 10) CREATE or UPDATE from one save button.
old_save_contact = "$('saveContact').onclick=async()=>{await dbApi('bg_contact','UPDATE',{filters:{id:editContact.id},data:{first_contact_date:$('editDate').value||null,email:$('editEmail').value.trim()||null,bgg_username:$('editBgg').value.trim()||null,source_game_name:$('editSource').value.trim()||null,heard_back:modalHeard,notes:$('editNotes').value.trim()||null,updated_at:new Date().toISOString()}});await loadContacts();closeM('contactModal')}"
new_save_contact = "$('saveContact').onclick=async()=>{let name=$('editName').value.trim();if(!name){alert('Name is required');$('editName').focus();return}let data={name,organization:$('editOrganization').value.trim()||null,first_contact_date:$('editDate').value||null,email:$('editEmail').value.trim()||null,bgg_username:$('editBgg').value.trim()||null,discord_username:$('editDiscord').value.trim()||null,preferred_contact_method:$('editPreferred').value||null,source_game_name:$('editSource').value.trim()||null,heard_back:modalHeard,notes:$('editNotes').value.trim()||null,updated_at:new Date().toISOString()};$('saveContact').disabled=true;try{if(editContact){await dbApi('bg_contact','UPDATE',{filters:{id:editContact.id},data})}else if(draftContact){await dbApi('bg_contact','CREATE',{data:{...data,bgg_type:draftContact.bgg_type,bgg_id:draftContact.bgg_id,source_game_id:draftContact.source_game_id}})}await loadContacts();closeM('contactModal');if(contactReturnGameId){let id=contactReturnGameId;contactReturnGameId=null;openGame(String(id))}}finally{$('saveContact').disabled=false}}"
replace_once(old_save_contact, new_save_contact, "contact create/update save")

# Delete only applies to an existing contact and should not leave stale return state.
old_delete = "$('deleteContact').onclick=async()=>{if(editContact&&confirm('Delete '+editContact.name+'?')){await dbApi('bg_contact','DELETE',{filters:{id:editContact.id}});await loadContacts();closeM('contactModal')}}"
new_delete = "$('deleteContact').onclick=async()=>{if(editContact&&confirm('Delete '+editContact.name+'?')){await dbApi('bg_contact','DELETE',{filters:{id:editContact.id}});await loadContacts();closeM('contactModal');if(contactReturnGameId){let id=contactReturnGameId;contactReturnGameId=null;openGame(String(id))}}}"
replace_once(old_delete, new_delete, "contact delete return")

# Version marker makes verification easy and keeps the patch idempotent at the workflow level.
s = s.replace('</body></html>', '<!-- contacts-crm-v2-2026-09-01 --></body></html>', 1)

TARGET.write_text(s, encoding="utf-8")
print("Upgraded bgg-contacts.html with single-step contact capture + Discord CRM fields")
